# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m6ilwzX2qZNwazgHmuCJNZcaWshyYNLv

# **Lab 1 - Introduction to Python programming I**

Enter your code in the spaces provided.  Do not change any of the variable names or function names that are already provided for you.  In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab1"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your name, section number, and BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="Tommy"

last_name="Morgan"

# Enter your Math 215 section number in between the quotation marks. 

section_number="001"  

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER!

BYUNetID="morganto"

"""**Problem 1**"""

my_first_var=((118+(11*2))/(9-2))   # Replace the value of 0 with the required expression from Problem 1.

"""**Problem 2**"""

def arithmetic2(i): 
  return ((i+2)*3)-5 # Put your return value here.  Your shouldn't need to add any more lines of code to this function.

"""**Problem 3**"""

def triple(y):
  return 3*y # Put your return value here.

def avg(x,y):
  return (x+y)/2 # Put your return value here.

def combine(x,y):
  y = triple(y) # Put your code here.  Remember that this function should call both of the functions triple(y) and avg(x,y) from above.
  return avg(x,y) # Put your return value here.

"""**Problem 4**"""

def first(c):
  # if the input is already defined as a list, then...
  return c[0] # this returns the first element in the list c.

def first_last(c):
  # second verse, same as the first...
  return c[0], c[-1] # :)

def middle(c):
  # hmm.
  return c[1:-1] # this worked on every list i tested

"""**Problem 5**"""

def swap(c):
  new_list=c.copy() # This creates a copy of the list c, which is called new_list.  Your function should work with this list instead of the list c which is passed to the function.
  oldfirst=new_list[0]
  newfirst=new_list[-1]
  new_list[0]=newfirst
  new_list[-1]=oldfirst
  return new_list # Put your return value here.

"""**Problem 6**"""

def absolute_value(x):
  if x<0: 
    return -1*x
  else:
    return x

"""**Problem 7**"""

def indicator(lower,upper,n):
  if lower <= n <= upper:
    return 1
  else: 
    return 0 # Put your return value here.

"""**Problem 8**"""

def trunc_max(x,y):
  if x>y:
    if x>0:
      return x
    else:
      return 0
  else:    
    if y>x:
      if y>0:
        return y
      else:
        return 0
    else:
      return 0

        # this returns 0 if the values are the same...
        # i.e. there is no greater of the two.

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.
"""